### ISSUE TITLE
Overview 30% (9/10)

### ISSUE THREAD

**Issue by kasperpagh** [tjaydk/IndexingBlog#1]
You manage to give a really nice introduction and keep a consistent narrative for the entire blog post.
However there are few points where more care could have been given to proof reading the blog. Some of us also felt that it would have been nice if you'd introduced the fact that you used MariaDB earlier.

Exceeds expectation 9/10 points

**Comment by Ebski** [comment]
Proof read the blog. Don't thing that MariaDB should be mentioned earlier as the blog is about relationel databases in general which is stated in the first line.
